tools/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :messages
  get 'main/index'

  root 'main#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

tools/app/models/message.rb
class Message < ActiveRecord::Base
end

tools/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

end

tools/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    @user = User.find_by_id(session[:current_user_id] = 1)
  end
  def update
  end
end

tools/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

tools/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:msg, :uid)
    end
end

tools/app/controllers/sessions_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
  end

  def destroy
  end

end

tools/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        redirect_to '/signup'
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password_digest, :password_confirm)
    end
end

tools/app/helpers/application_helper.rb
module ApplicationHelper
end

tools/app/helpers/main_helper.rb
module MainHelper
end

tools/app/helpers/messages_helper.rb
module MessagesHelper
end

tools/app/helpers/users_helper.rb
module UsersHelper
end

tools/app/views/layouts/_header.html.erb
<table class="overall_header">
  <tr>
    <td>
      <div class="welcome_msg">
        Welcome, <%= @user %> !
      </div>
    </td>
    <td>
      <div class="toolbar">
        <%= link_to 'Signup', '/signup' %>
        <%= link_to 'Login', '/login' %>
      </div>
    </td>
  </tr>
</table>

tools/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tools</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="main_contents">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

tools/app/views/main/index.html.erb
<h1>Welcome !</h1>

tools/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_field :msg %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.number_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tools/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

tools/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Msg</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.msg %></td>
        <td><%= message.uid %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

tools/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

tools/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Msg:</strong>
  <%= @message.msg %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @message.uid %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

tools/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div class="field_label">
          Name
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.text_field :name %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field_label">
          Password
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.password_field :password_digest %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field_label">
          Confirmation
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.password_field :password_confirm %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="actions">
          <%= f.submit %>
        </div>
      </td>
    </tr>
  </table>

<% end %>

tools/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

tools/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password digest</th>
      <th>Password confirm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.password_confirm %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

tools/app/views/users/new.html.erb
<h1>Signup !</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

tools/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Password confirm:</strong>
  <%= @user.password_confirm %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>